SET SESSION sql_mode = ''; SET GLOBAL local_infile=1;

USE avodb;

LOAD DATA INFILE 'C:\PAISES.csv'
INTO TABLE paises
FIELDS TERMINATED BY '\t' ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;